stages:
    - build
    - push
    - deploy

build_image:
  stage: build
  script:
    - ls -la
    - set -xe
    - cd uifiles
    - npm install --registry=https://registry.npm.taobao.org
    - node ./node_modules/webpack/bin/webpack.js
    - cd ..
    - CI_COMMIT_TAG=`git log | grep -e "^commit.*" | wc -l`
    - docker build --pull -t "$CI_REGISTRY_EPTC_IMAGE:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY_EPTC_IMAGE:$CI_COMMIT_TAG"
    - docker rmi "$CI_REGISTRY_EPTC_IMAGE:$CI_COMMIT_TAG"
  only:
    - mergeBranch
  tags:
    - etback


